---
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
.travis.yml:
  delete: true

.rubocop.yml:
  default_configs:
    inherit_from: ".rubocop_todo.yml"
    AllCops:
      NewCops: enable
      Include:
        - "rakelib/*.rake"
      Exclude:
        - ".modules/**/*"
    Style/SingleLineMethods:
      Exclude:
        - "rakelib/test.rake"

Rakefile:
  default_disabled_lint_checks:
    - '140chars'

spec/spec_helper.rb:
  coverage_report: true
spec/default_facts.yml:
  delete: true
