---
HOSTS:
  ubuntu-1804:
    platform: ubuntu-18.04-amd64
    image: library/ubuntu:18.04
    hypervisor: docker
    roles:
      - default

CONFIG:
  type: aio
  docker_options:
    platform: linux/amd64
